#!/bin/sh
echo ""
echo "peek installed. To enable in your shell, add one line to your rc file:"
echo ""
echo "  zsh  — add to ~/.zshrc:"
echo "    source /usr/share/peek/shell/zsh/peek.zsh"
echo ""
echo "  bash — add to ~/.bashrc:"
echo "    source /usr/share/peek/shell/bash/peek.bash"
echo ""
echo "Then open a new terminal (or source the file)."
